### ISSUE TITLE
IllegalStateExceptions on logout after reload.

### ISSUE THREAD

**Issue by RaphaelWoude** [ThatKawaiiSam/Assemble#14]
Hello,

Thank you so much for creating this library. I really appreciate it.
After some tinkering with the lib I found that if you are online on the server and you reload the server, then proceed to log out, the console will spam IllegalStateExceptions.
```JAVA
// Console
[17:42:48 WARN]: java.lang.IllegalStateException: Asynchronous scoreboard creation!
[17:42:48 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[17:42:48 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:45)
[17:42:48 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:28)
[17:42:48 WARN]:        at io.github.thatkawaiisam.assemble.AssembleBoard.getScoreboard(AssembleBoard.java:48)
[17:42:48 WARN]:        at io.github.thatkawaiisam.assemble.AssembleThread.tick(AssembleThread.java:50)
[17:42:48 WARN]:        at io.github.thatkawaiisam.assemble.AssembleThread.run(AssembleThread.java:29)
[17:42:48 WARN]: io.github.thatkawaiisam.assemble.AssembleException: There was an error updating Sympatic's scoreboard.
[17:42:48 WARN]:        at io.github.thatkawaiisam.assemble.AssembleThread.tick(AssembleThread.java:122)
[17:42:48 WARN]:        at io.github.thatkawaiisam.assemble.AssembleThread.run(AssembleThread.java:29)
```
This is my implementation:
```JAVA
// Setup
Assemble assemble = new Assemble(this, new ScoreboardAdapter(this));
assemble.setTicks(5);
assemble.setAssembleStyle(AssembleStyle.MODERN);
assemble.setup();
```

```JAVA
// Adapter
public class ScoreboardAdapter implements AssembleAdapter {

    @Override
    public String getTitle(Player player) {
        return ChatColor.GOLD + ChatColor.BOLD.toString() + "Reflection";
    }

    @Override
    public List<String> getLines(Player player) {
        List<String> lines = new ArrayList<>();

        lines.add(ChatColor.GREEN + ChatColor.BOLD.toString() + "PVP Timer: " + ChatColor.GRAY + "05:00");

        if (lines.size() > 0) {
            lines.add(0, ChatColor.GRAY + ChatColor.STRIKETHROUGH.toString() + "----------------------");
            lines.add(ChatColor.GRAY + ChatColor.STRIKETHROUGH.toString() + "----------------------");
        }

        return lines;
    }

}
```

**Comment by RaphaelWoude** [comment]
Debugged some more and it seems that you will need to run the `cleanup()` when the server reloads.
